export const AUTH_USER = 'authUser';
export const AUTH_ERROR_MESSAGE = 'authErrorMessage';
export const AUTH_SUCCESS_MESSAGE = 'authSuccessMessage';
export const SET_AUTH_NON_SIGNED_IN_USER = 'setAuthNonSignedInUser';
export const SHOW_NON_SIGNED_IN_USER_MESSAGE = 'showNonSignedInUserMessage';
export const SIGNIN_REQUEST = 'signinRequest';
export const SIGNOUT_SUCCESS = 'signOutSuccess';
export const SIGNIN_SUCCESS = 'signinSuccess';
export const SIGNUP_SUCCESS = 'signupSuccess';
export const REMOVER_SPINNER = 'removeSpinner';
export const ADD_SPINNER = 'addSpinner';
export const SHOW_MODAL = 'showModal';
export const HIDE_MODAL = 'hideModal';
export const SHOW_LOADER_MODAL = 'showLoadermodal';
export const HIDE_LOADER_MODAL = 'hideLoadermodal';
export const SHOW_POPUP = 'showPopup';
export const HIDE_POPUP = 'hidePopup';
export const ADD_NOTIFICATION = 'add_notification';
export const REMOVE_NOTIFICATION = 'remove_notification';
export const CONCRETE_ADD_PAVEMENT_STRUCTURE_TYPE = 'concreteAddPavementStructureType';
export const CONCRETE_REMOVE_PAVEMENT_STRUCTURE_TYPE = 'concreteRemovePavementStructureType';
export const CREATE_NEW_PROJECT = 'create_new_project';
export const CONCRETE_SET_CUSTOM_TRAFFIC_SPECTRUM_FORM_VALUES = 'concreteSetCustomFormValues';
export const CONCRETE_SET_INITIAL_CUSTOM_TRAFFIC_SPECTRUM_FORM_VALUES = 'concreteSetInitialCustomTrafficSpectrumFormValues';
export const CONCRETE_SET_TRAFFIC_SUMMARY_FORM_VALUES ='concreteTrafficSummaryFormValues';
export const CONCRETE_SET_K_VALUE_GRAPH_VALUES ='concreteKValueGraphSummaryFormValues';
export const CONCRETE_SET_FLEXURAL_STRENGTH_GRAPH_VALUES ='concreteFlexuralStrengthGraphSummaryFormValues';
export const CONCRETE_SET_RELIABILITY_GRAPH_VALUES ='concreteReliabilityGraphSummaryFormValues';
export const CONCRETE_SET_DESIGN_LIFE_GRAPH_VALUES ='concreteDesignLifeGraphSummaryFormValues';
export const CONCRTE_EDIT_ASPHALT_ANALYSIS_BUTTON ='concreteEditAsphaltAnalysis';
export const CONCRETE_EDIT_DEFAULT_ASPHALT_ANALYSIS_PARAMETRES ='concreteEditDefaultAsphaltAnalysisParametres';
export const CONCRETE_SET_ASPHALT_ANALSIS_FORM_VALUES ='concreteSetConcreteAsphaltAnalysisFormValues';
export const UPDATE_CONCRETE_ASPHALT_ANALSIS_FORM_VALUES ='updateConcreteAsphaltAnalysisFormValues';
export const CONCRETE_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='concreteSetCompositeKValueRadioButtonValue';

export const CONCRETE_SET_JPCP_DOWELED_K_VALUE_GRAPH_VALUES ='concreteJpcpDoweledKValueGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_UNDOWELED_K_VALUE_GRAPH_VALUES ='concreteJpcpUndoweledKValueGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_DOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='concreteJpcpDoweledFlexualStrengthGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_UNDOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='concreteJpcpUndoweledFLexuralStrengthGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_DOWELED_RELIABILITY_GRAPH_VALUES ='concreteJpcpDoweledReliabilityGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_UNDOWELED_RELIABILITY_GRAPH_VALUES ='concreteJpcpUndoweledReliabilityGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_DOWELED_DESIGN_LIFE_GRAPH_VALUES ='concreteJpcpDoweledDesignLifeGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_UNDOWELED_DESIGN_LIFE_GRAPH_VALUES ='concreteJpcpUndoweledDesignLifeGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_DOWELED_CRACKING_VALUES ='concreteJpcpDoweledCrackingValues';
export const CONCRETE_SET_JPCP_UNDOWELED_CRACKING_VALUES ='concreteJpcpUndoweledCrackingValues';
export const CONCRETE_SET_JPCP_DOWELED_FAULTING_VALUES ='concreteJpcpDoweledFaultingValues';
export const CONCRETE_SET_JPCP_UNDOWELED_FAULTING_VALUES ='concreteJpcpUndoweledFaultingValues';
export const CONCRETE_SET_JPCP_DOWELED_FATIGUE_USED_VALUE ='concreteJpcpDoweledFatigueUsedValue';
export const CONCRETE_SET_JPCP_UNDOWELED_FATIGUE_USED_VALUE ='concreteJpcpUndoweledFatigueUsedValue';
export const CONCRETE_SET_JPCP_DOWELED_EROSION_USED_VALUE ='concreteJpcpDoweledErosionUsedValue';
export const CONCRETE_SET_JPCP_UNDOWELED_EROSION_USED_VALUE ='concreteJpcpUndoweledErosionUsedValue';
export const CONCRETE_SET_JPCP_DOWELED_SLABS_CRACKED_GRAPH_VALUES ='concreteJpcpDoweledSlabsCrackedGraphSummaryFormValues';
export const CONCRETE_SET_JPCP_UNDOWELED_SLABS_CRACKED_GRAPH_VALUES ='concreteJpcpUndoweledSlabsCrackedGraphSummaryFormValues';

export const CONCRETE_SET_RCC_K_VALUE_GRAPH_VALUES ='concreteRccKValueGraphSummaryFormValues';
export const CONCRETE_SET_RCC_FLEXURAL_STRENGTH_GRAPH_VALUES ='rccFlexuralStrengthGraphSummaryFormValues';
export const CONCRETE_SET_RCC_RELIABILITY_GRAPH_VALUES ='concreteRccReliabilityGraphSummaryFormValues';
export const CONCRETE_SET_RCC_DESIGN_LIFE_GRAPH_VALUES ='concreteRccDesignLifeGraphSummaryFormValues'; 
export const CONCRETE_SET_RCC_SLABS_CRACKED_GRAPH_VALUES ='concreteRccSlabsCrackedGraphSummaryFormValues'; 
export const CONCRETE_SET_RCC_FATIGUE_USED_VALUE ='concreteRccFatigueUsedValue';
export const CONCRETE_SET_RCC_EROSION_USED_VALUE  ='concreteRccErosionUsedValue';
export const CONCRETE_SET_RCC_CRACKING_VALUES ='concreteRccCrackingValues';
export const CONCRETE_SET_RCC_FAULTING_VALUES  ='concreteRccFaultingValues';
export const CONCRETE_SET_MRSG_INPUT_VALUE  ='concreteMrsgInputValue';
export const CONCRETE_EDIT_ASPHALT_ANALYSIS_BUTTON  ='concreteEditAsphaltAnalysisButton';
export const CONCRETE_SET_TRAFFIC_FORM_INPUTS_DROPDOWN_DISABLED ='concreteSetTrafficFormInputsDisbaled';

//Overlay
export const OVERLAY_ADD_PAVEMENT_STRUCTURE_TYPE  ='overlayAddPavementStructureType';
export const OVERLAY_REMOVE_PAVEMENT_STRUCTURE_TYPE  ='overlayRemovePavementStructureType';
export const OVERLAY_SET_CUSTOM_TRAFFIC_SPECTRUM_FORM_VALUES  ='overlaySetCustomFormValues';
export const OVERLAY_SET_INITIAL_CUSTOM_TRAFFIC_SPECTRUM_FORM_VALUES  ='overlaySetInitialCustomTrafficSpectrumValues';
export const OVERLAY_SET_TRAFFIC_SUMMARY_FORM_VALUES  ='overlaySetTrafficSummaryFormValues';
export const OVERLAY_SET_K_VALUE_GRAPH_VALUES ='overlaySetKValueGraphValues';
export const OVERLAY_SET_FLEXURAL_STRENGTH_GRAPH_VALUES  ='overlaySetFlexuralStrengthGraphValues';
export const OVERLAY_SET_RELIABILITY_GRAPH_VALUES  ='overlaySetReliabilityGraphValues';
export const OVERLAY_SET_DESIGN_LIFE_GRAPH_VALUES  ='overlaySetDesignLifeGraphValues';
export const OVERLAY_EDIT_ASPHALT_ANALYSIS_BUTTON  ='overlayEditAsphaltAnalysisButton';
export const OVERLAY_EDIT_DEFAULT_ASPHALT_ANALYSIS_PARAMETRES ='overlayEditDefaultAsphaltAnalysisParametres';
export const OVERLAY_SET_ASPHALT_ANALSIS_FORM_VALUES  ='overlaySetConcreteAsphaltAnalysisFormValues';
export const UPDATE_OVERLAY_ASPHALT_ANALSIS_FORM_VALUES  ='updateOverlayAsphaltAnaysisFormValues';
export const OVERLAY_SET_TRAFFIC_FORM_INPUTS_DROPDOWN_DISABLED ='overlaySetTrafficFormInputsDisbaled';
export const OVERLAY_SET_MRSG_INPUT_VALUE  ='overlaySetMrsgInputValue';
export const OVERLAY_UNBONDED_ASPHALT_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='overlayUnbondedAsphaltSetCompositeKValueRadioButtonValue';
export const OVERLAY_BONDED_CONCRETE_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='overlayBondedConcreteSetCompositeKValueRadioButtonValue';
export const OVERLAY_UNBONDED_CONCRETE_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='overlayUnbondedConcreteSetCompositeKValueRadioButtonValue';

//New Composite
export const NEW_COMPOSITE_SET_CUSTOM_TRAFFIC_SPECTRUM_FORM_VALUES  ='newCompositeSetCustomTrafficSpectrumFormValues';
export const NEW_COMPOSITE_SET_INITIAL_CUSTOM_TRAFFIC_SPECTRUM_FORM_VALUES ='newCompositeSetInitialTrafficSpectrumCustomFormValues';
export const NEW_COMPOSITE_SET_TRAFFIC_SUMMARY_FORM_VALUES  ='newCompsiteSetTrafficSummaryFormValues';
export const NEW_COMPOSITE_ADD_PAVEMENT_STRUCTURE_TYPE  ='newCompositeAddPavementStructureType';
export const NEW_COMPOSITE_SET_CURRENT_PROJECT_VALUES  ='newCompositeSetCurrentProjectValues';

export const NEW_COMPOSITE_JPCP_SET_DOWELED_K_VALUE_GRAPH_VALUES ='newCompositeJpcpDoweledKValueGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_K_VALUE_GRAPH_VALUES ='newCompositeJpcpUndoweledKValueGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='newCompositeJpcpDoweledFlexualStrengthGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='newCompositeJpcpUndoweledFLexuralStrengthGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_RELIABILITY_GRAPH_VALUES ='newCompositeJpcpDoweledReliabilityGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_RELIABILITY_GRAPH_VALUES ='newCompositeJpcpUndoweledReliabilityGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_DESIGN_LIFE_GRAPH_VALUES ='newCompositeJpcpDoweledDesignLifeGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_DESIGN_LIFE_GRAPH_VALUES ='newCompositeJpcpUndoweledDesignLifeGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_CRACKING_VALUES ='newCompositeJpcpDoweledCrackingValues';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_CRACKING_VALUES ='newCompositeJpcpUndoweledCrackingValues';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_FAULTING_VALUES ='newCompositeJpcpDoweledFaultingValues';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_FAULTING_VALUES ='newCompositeJpcpUndoweledFaultingValues';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_FATIGUE_USED_VALUE ='newCompositeJpcpDoweledFatigueUsedValue';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_FATIGUE_USED_VALUE ='newCompositeJpcpUndoweledFatigueUsedValue';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_EROSION_USED_VALUE ='newCompositeJpcpDoweledErosionUsedValue';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_EROSION_USED_VALUE ='newCompositeJpcpUndoweledErosionUsedValue';
export const NEW_COMPOSITE_JPCP_SET_DOWELED_SLABS_CRACKED_GRAPH_VALUES  ='newCompositeJpcpDoweledSlabsCrackedGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_UNDOWELED_SLABS_CRACKED_GRAPH_VALUES ='newCompositeJpcpUndoweledSlabsCrackedGraphSummaryFormValues';
export const NEW_COMPOSITE_JPCP_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='newCompositeJpcpSetCompositeKValueRadioButtonValue';

export const NEW_COMPOSITE_RCC_SET_K_VALUE_GRAPH_VALUES ='newCompositeRccKValueGraphSummaryFormValues';
export const NEW_COMPOSITE_RCC_SET_FLEXURAL_STRENGTH_GRAPH_VALUES ='newCompositeRccFlexuralStrengthGraphSummaryFormValues';
export const NEW_COMPOSITE_RCC_SET_RELIABILITY_GRAPH_VALUES ='newCompositeRccReliabilityGraphSummaryFormValues';
export const NEW_COMPOSITE_RCC_SET_DESIGN_LIFE_GRAPH_VALUES ='newCompositeRccDesignLifeGraphSummaryFormValues'; 
export const NEW_COMPOSITE_RCC_SET_SLABS_CRACKED_GRAPH_VALUES ='newCompositeRccSlabsCrackedGraphSummaryFormValues'; 
export const NEW_COMPOSITE_RCC_SET_FATIGUE_USED_VALUE ='newCompositeRccFatigueUsedValue';
export const NEW_COMPOSITE_RCC_SET_EROSION_USED_VALUE  ='newCompositeRccErosionUsedValue';
export const NEW_COMPOSITE_RCC_SET_CRACKING_VALUES ='newCompositeRccCrackingValues';
export const NEW_COMPOSITE_RCC_SET_FAULTING_VALUES  ='newCompositeRccFaultingValues';
export const NEW_COMPOSITE_RCC_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='newCompositeRccSetCompositeKValueRadioButtonValue';


export const NEW_COMPOSITE_ASPHALT_HDG_SUMMARY_FORM_DESIGN_LAYER_VALUES ='newCompositeHdgSummaryFormGraphDesignLayerValue';
export const NEW_COMPOSITE_ASPHALT_BST_SUMMARY_FORM_DESIGN_LAYER_VALUES ='newCompositeBstSummaryFormGraphDesignLayerValue';
export const NEW_COMPOSITE_ASPHALT_OTHER_SUMMARY_FORM_DESIGN_LAYER_VALUES ='newCompositeOtherSummaryFormGraphDesignLayerValue';

export const NEW_COMPOSITE_ASPHALT_HDG_SUMMARY_FORM_GRAPH_VALUES ='newCompositeHdgSummaryFormGraphValue';
export const NEW_COMPOSITE_ASPHALT_BST_SUMMARY_FORM_GRAPH_VALUES ='newCompositeBstSummaryFormGraphValue';
export const NEW_COMPOSITE_ASPHALT_OTHER_SUMMARY_FORM_GRAPH_VALUES ='newCompositeOtherSummaryFormGraphValue';

export const NEW_COMPOSITE_ASPHALT_OTHER_SUMMARY_FORM_DAMAGE_REFERENCE_LINE_VALUES ='newCompositeHdgSummaryFormGraphReferenceLineValues';
export const NEW_COMPOSITE_ASPHALT_HDG_SUMMARY_FORM_DAMAGE_REFERENCE_LINE_VALUES ='newCompositeBstSummaryFormGraphReferenceLineValues';
export const NEW_COMPOSITE_ASPHALT_BST_SUMMARY_FORM_DAMAGE_REFERENCE_LINE_VALUES ='newCompositeOtherSummaryFormGraphReferenceLineValues';

export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_K_VALUE_GRAPH_VALUES ='overlayUnbondedAsphaltDoweledKValueGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_K_VALUE_GRAPH_VALUES ='overlayUnbondedAsphaltUndoweledKValueGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='overlayUnbondedAsphaltDoweledFlexualStrengthGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='overlayUnbondedAsphaltUndoweledFLexuralStrengthGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_RELIABILITY_GRAPH_VALUES ='overlayUnbondedAsphaltDoweledReliabilityGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_RELIABILITY_GRAPH_VALUES ='overlayUnbondedAsphaltUndoweledReliabilityGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_DESIGN_LIFE_GRAPH_VALUES ='overlayUnbondedAsphaltDoweledDesignLifeGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_DESIGN_LIFE_GRAPH_VALUES ='overlayUnbondedAsphaltUndoweledDesignLifeGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_CRACKING_VALUES ='overlayUnbondedAsphaltDoweledCrackingValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_CRACKING_VALUES ='overlayUnbondedAsphaltUndoweledCrackingValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_FAULTING_VALUES ='overlayUnbondedAsphaltDoweledFaultingValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_FAULTING_VALUES ='overlayUnbondedAsphaltUndoweledFaultingValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_FATIGUE_USED_VALUE ='overlayUnbondedAsphaltDoweledFatigueUsedValue';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_FATIGUE_USED_VALUE ='overlayUnbondedAsphaltUndoweledFatigueUsedValue';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_EROSION_USED_VALUE ='overlayUnbondedAsphaltDoweledErosionUsedValue';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_EROSION_USED_VALUE ='overlayUnbondedAsphaltUndoweledErosionUsedValue';
export const OVERLAY_UNBONDED_ASPHALT_SET_DOWELED_SLABS_CRACKED_GRAPH_VALUES ='overlayUnbondedAsphaltDoweledSlabsCrackedGraphSummaryFormValues';
export const OVERLAY_UNBONDED_ASPHALT_SET_UNDOWELED_SLABS_CRACKED_GRAPH_VALUES ='overlayUnbondedAsphaltUndoweledSlabsCrackedGraphSummaryFormValues';

export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_K_VALUE_GRAPH_VALUES ='overlayUnbondedConcreteDoweledKValueGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_K_VALUE_GRAPH_VALUES ='overlayUnbondedConcreteUndoweledKValueGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='overlayUnbondedConcreteDoweledFlexualStrengthGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_FLEXURAL_STRENGTH_GRAPH_VALUES ='overlayUnbondedConcreteUndoweledFLexuralStrengthGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_RELIABILITY_GRAPH_VALUES ='overlayUnbondedConcreteDoweledReliabilityGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_RELIABILITY_GRAPH_VALUES ='overlayUnbondedConcreteUndoweledReliabilityGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_DESIGN_LIFE_GRAPH_VALUES ='overlayUnbondedConcreteDoweledDesignLifeGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_DESIGN_LIFE_GRAPH_VALUES ='overlayUnbondedConcreteUndoweledDesignLifeGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_CRACKING_VALUES ='overlayUnbondedConcreteDoweledCrackingValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_CRACKING_VALUES ='overlayUnbondedConcreteUndoweledCrackingValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_FAULTING_VALUES ='overlayUnbondedConcreteDoweledFaultingValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_FAULTING_VALUES ='overlayUnbondedConcreteUndoweledFaultingValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_FATIGUE_USED_VALUE ='overlayUnbondedConcreteDoweledFatigueUsedValue';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_FATIGUE_USED_VALUE ='overlayUnbondedConcreteUndoweledFatigueUsedValue';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_EROSION_USED_VALUE ='overlayUnbondedConcreteDoweledErosionUsedValue';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_EROSION_USED_VALUE ='overlayUnbondedConcreteUndoweledErosionUsedValue';
export const OVERLAY_UNBONDED_CONCRETE_SET_DOWELED_SLABS_CRACKED_GRAPH_VALUES ='overlayUnbondedConcreteDoweledSlabsCrackedGraphSummaryFormValues';
export const OVERLAY_UNBONDED_CONCRETE_SET_UNDOWELED_SLABS_CRACKED_GRAPH_VALUES ='overlayUnbondedConcreteUndoweledSlabsCrackedGraphSummaryFormValues';


export const OVERLAY_BONDED_CONCRETE_SET_K_VALUE_GRAPH_VALUES ='overlayBondedConcreteKValueGraphSummaryFormValues';
export const OVERLAY_BONDED_CONCRETE_SET_FLEXURAL_STRENGTH_GRAPH_VALUES ='overlayBondedConcreteFlexuaGraphSummaryFormValues';
export const OVERLAY_BONDED_CONCRETE_SET_RELIABILITY_GRAPH_VALUES ='overlayBondedConcreteReliabilityGraphSummaryFormValues';
export const OVERLAY_BONDED_CONCRETE_SET_DESIGN_LIFE_GRAPH_VALUES ='overlayBondedConcreteDesignLifeGraphSummaryFormValues';
export const OVERLAY_BONDED_CONCRETE_SET_SLABS_CRACKED_GRAPH_VALUES ='overlayBondedConcreteSlabsCrackedGraphSummaryFormValues';
export const OVERLAY_BONDED_CONCRETE_SET_EROSION_USED_VALUE ='overlayBondedConcreteErosionUsedValue';
export const OVERLAY_BONDED_CONCRETE_SET_FATIGUE_USED_VALUE ='overlayBondedConcreteFatigueUsedValue';
export const OVERLAY_BONDED_CONCRETE_SET_CRACKING_VALUES ='overlayBondedConcreteCrackingValues';
export const OVERLAY_BONDED_CONCRETE_SET_FAULTING_VALUES ='overlayBondedConcreteFaultingValues';

//Parking
export const PARKING_PAVEMENT_STRUCTURE_SET_ROW_CHOSEN ='parkingPavementStructureRowChosen';

export const PARKING_SET_K_VALUE_GRAPH_VALUES ='parkingKValueGraphSummaryFormValues';
export const PARKING_SET_FLEXURAL_STRENGTH_GRAPH_VALUES ='parkingFlexuralStrengthGraphSummaryFormValues';
export const PARKING_SET_RELIABILITY_GRAPH_VALUES ='parkingReliabilityGraphSummaryFormValues';
export const PARKING_SET_DESIGN_LIFE_GRAPH_VALUES ='parkingDesignLifeGraphSummaryFormValues'; 
export const PARKING_SET_SLABS_CRACKED_GRAPH_VALUES ='parkingSlabsCrackedGraphSummaryFormValues'; 
export const PARKING_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='parkingSetCompositeKValueRadioButtonValue';
export const PARKING_SET_TRAFFIC_SUMMARY_FORM_VALUES = 'parkingTrafficSummaryFormValues';

export const PARKING_SET_FATIGUE_USED_VALUE = 'ParkingFatigueUsedValue';
export const PARKING_SET_EROSION_USED_VALUE = 'ParkingErosionUsedValue';
export const PARKING_SET_CRACKING_VALUES = 'ParkingCrackingValues';
export const PARKING_SET_FAULTING_VALUES = 'ParkingFaultingValues';

// Project Dashabord
export const MY_PROJECTS_SET_CURRENTLY_SELECTED_FOLDER = 'myProjectsSetCurrentltSelectedFolder';
export const CONCRETE_SET_CURRENT_PROJECT_VALUES= 'newCompositeSetCurrentProjectValues';
export const PARKING_SET_CURRENT_PROJECT_VALUES= 'parkingSetCurrentProjectValues';
export const OVERLAY_SET_CURRENT_PROJECT_VALUES= 'overlaySetCurrentProjectValues';

export const RESET_POPUP_TO_INITIAL_STATE = 'resetPopupToInitialState';
export const RESET_MODAL_TO_INITIAL_STATE = 'resetModalToInitialState';
export const RESET_NOTIFICATION_TO_INITIAL_STATE = 'resetNotificationToInitialState';
export const SET_USER_PROJECTS = 'setLoggedInUserProjects';
export const SET_USER_FOLDERS = 'setLoggedInUserFolders';
export const ADD_USER_FOLDER = 'addOrEditFolder';
export const ADD_FOLDER_ERROR_MESSAGE = 'addFolderErrorMessage';
export const ADD_FOLDER_ADD_SPINNER = 'addFolderAddSpinner';
export const ADD_FOLDER_REMOVE_SPINNER = 'addFolderRemoveSpinner';

export const ADD_PROJECT_ERROR_MESSAGE = 'addProjectErrorMessage';
export const ADD_PROJECT_SHARE_ERROR_MESSAGE = 'addProjectShareErrorMessage';
export const ADD_PROJECT_ADD_SPINNER = 'addProjectAddSpinner';
export const ADD_PROJECT_REMOVE_SPINNER = 'addProjectRemoveSpinner';

export const SET_PROJECT_TYPE = 'currentlySelectedProjectType';
export const SET_PROJECT_NAME = 'currentlySelectedProjectName';
export const SET_PROJECT_ID = 'currentlySelectedProjectId';

export const ADD_USER_PROJECT = 'addOrEditProject';
export const UPDATE_USER_PROJECT = 'updateUserProject';

export const SET_PROJECT_DESCRIPTION = 'currentlySelectedProjectDescription';
export const SET_PROJECT_ROUTE = 'currentlySelectedProjectRoute';
export const SET_PROJECT_OWNERS_AGENCY = 'currentlySelectedProjectOwnersAgency';
export const SET_PROJECT_ZIP_CODE = 'currentlySelectedProjectZipCode';
export const SET_PROJECT_UNIT_TYPE = 'currentlySelectedProjectUnitType';
export const SET_PROJECT_CREATED_DATE = 'currentlySelectedProjectCreatedDate';
export const SET_PROJECT_LAST_MODIFIED_DATE = 'currentlySelectedProjectLastModifiedDate';
export const SET_PROJECT_DESIGNER = 'currentlySelectedProjectDesigner';
export const SET_PROJECT_FOLDER_ID = 'currentlySelectedProjectFolderId';

export const SET_CURRENT_PROJECT_FORMTYPE = 'setCurrentProjectFormType';
export const SET_STATE_TO_INITIAL_STATE = 'setStateToInitialState';
export const SET_CURRENT_SELECTED_PROJECT_ID = 'setCurrentSelectedProjectId';
export const SET_STORE_STATE_TO_NILL = 'setStoreStateToNull';

export const SET_INTERMODAL_ADD_VEHICLE_WHEEL_COUNT = 'setWheelCount';
export const SET_INTERMODAL_ADD_VEHICLE_WHEEL_POSITIONS = 'setWheelPostions';
export const INTERMODAL_SET_CURRENT_PROJECT_VALUES = 'intermodalSetCurrentProjectValues';

//Intermodal
export const SET_USER_VEHICLES = 'setUserVehicles';
export const ADD_SELECTED_USER_VEHICLE = 'addSelectedUserVehicles';
export const REMOVE_SELECTED_USER_VEHICLE = 'removeSelectedUserVehicles';
export const INTERMODAL_SET_COMPOSITE_K_VALUE_RADIO_BUTTON_VALUE ='intermodalSetCompositeKValueRadioButtonValue';
export const INTERMODAL_SET_SUMMARY_PAGE_VEHICLES_INFO = 'setSummaryPageVehiclesInfo';
export const ADD_USER_VEHICLE = 'addUserVehicle';
export const UPDATE_USER_VEHICLE = 'updateUserVehicle';



